# Generated by Django 3.1.4 on 2020-12-07 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitability',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='suitability',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
