# Generated by Django 3.1.4 on 2020-12-09 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_profile', '0002_auto_20201207_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suitability',
        ),
    ]
